import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { ApiError, apiFetch, idempotencyHeaders } from "../api/client";
import type { Account } from "../api/types";
import { AsyncState } from "../components/AsyncState";
import { MoneyField } from "../components/MoneyField";
import { Page } from "../components/Page";
import { useAccounts } from "../hooks/useFinanceData";
import { formatDateBr } from "../lib/dates";
import { moneyText, requiredText, todayIso } from "../lib/forms";
import { formatBrl } from "../lib/money";

const accountSchema = z.object({ name: requiredText, institution: z.string(), balance: moneyText, referenceDate: z.string() });
const transferSchema = z.object({ from: requiredText, to: requiredText, amount: moneyText, date: z.string() }).refine((v) => v.from !== v.to, { message: "Escolha contas diferentes.", path: ["to"] });
const referenceSchema = z.object({ accountId: requiredText, balance: moneyText, date: z.string(), reason: requiredText });
type TransferPreview = { preview_token: string; amount_minor: number; source_balance_after_minor: number; target_balance_after_minor: number; consolidated_change_minor: number };
type ReferencePreview = { preview_token: string; current_balance_before_minor: number; current_balance_after_minor: number; difference_minor: number; covered_movement_count: number };

export function AccountsPage() {
  const accounts = useAccounts();
  const queryClient = useQueryClient();
  const [preview, setPreview] = useState<{ input: z.output<typeof transferSchema>; result: TransferPreview } | null>(null);
  const [editing, setEditing] = useState<Account | null>(null);
  const [editName, setEditName] = useState("");
  const [referencePreview, setReferencePreview] = useState<{ input: z.output<typeof referenceSchema>; result: ReferencePreview } | null>(null);
  const accountForm = useForm<z.input<typeof accountSchema>>({ resolver: zodResolver(accountSchema), defaultValues: { name: "", institution: "", balance: "0,00", referenceDate: todayIso() } });
  const transferForm = useForm<z.input<typeof transferSchema>>({ resolver: zodResolver(transferSchema), defaultValues: { from: "", to: "", amount: "", date: todayIso() } });
  const referenceForm = useForm<z.input<typeof referenceSchema>>({ resolver: zodResolver(referenceSchema), defaultValues: { accountId: "", balance: "", date: todayIso(), reason: "" } });
  const refresh = () => { void queryClient.invalidateQueries({ queryKey: ["accounts"] }); void queryClient.invalidateQueries({ queryKey: ["monthly"] }); };
  const add = useMutation({ mutationFn: (v: z.output<typeof accountSchema>) => apiFetch("/api/v1/accounts", { method: "POST", body: JSON.stringify({ name: v.name, institution: v.institution || null, reference_balance_minor: v.balance, reference_date: v.referenceDate }) }), onSuccess: () => { accountForm.reset(); refresh(); } });
  const requestTransfer = useMutation({ mutationFn: async (v: z.output<typeof transferSchema>) => ({ input: v, result: await apiFetch<TransferPreview>("/api/v1/transfers/preview", { method: "POST", body: JSON.stringify({ from_account_id: v.from, to_account_id: v.to, amount_minor: v.amount, planned_date: v.date, effective_date: v.date, status: "effective" }) }) }), onSuccess: setPreview });
  const transfer = useMutation({ mutationFn: (v: NonNullable<typeof preview>) => apiFetch("/api/v1/transfers/confirm", { method: "POST", headers: idempotencyHeaders(), body: JSON.stringify({ from_account_id: v.input.from, to_account_id: v.input.to, amount_minor: v.input.amount, planned_date: v.input.date, effective_date: v.input.date, status: "effective", preview_token: v.result.preview_token }) }), onSuccess: () => { setPreview(null); transferForm.reset(); refresh(); }, onError: (error) => { if (error instanceof ApiError && error.code === "STALE_PREVIEW" && error.detail?.preview) setPreview((current) => current ? { input: current.input, result: error.detail?.preview as TransferPreview } : null); } });
  const rename = useMutation({ mutationFn: (account: Account) => apiFetch(`/api/v1/accounts/${account.id}`, { method: "PUT", body: JSON.stringify({ name: editName, institution: account.institution, expected_revision: account.revision }) }), onSuccess: () => { setEditing(null); refresh(); } });
  const archive = useMutation({ mutationFn: (account: Account) => apiFetch(`/api/v1/accounts/${account.id}/archive`, { method: "POST", body: JSON.stringify({ expected_revision: account.revision, reason: "Arquivada pelo usuário" }) }), onSuccess: refresh });
  const requestReference = useMutation({ mutationFn: async (input: z.output<typeof referenceSchema>) => {
    const account = accounts.data?.items.find((item) => item.id === input.accountId);
    if (!account) throw new Error("Conta não encontrada.");
    return { input, result: await apiFetch<ReferencePreview>(`/api/v1/accounts/${account.id}/reference/preview`, { method: "POST", body: JSON.stringify({ reference_date: input.date, reference_balance_minor: input.balance, expected_revision: account.revision, reason: input.reason }) }) };
  }, onSuccess: setReferencePreview });
  const confirmReference = useMutation({ mutationFn: ({ input, result }: NonNullable<typeof referencePreview>) => {
    const account = accounts.data?.items.find((item) => item.id === input.accountId);
    if (!account) throw new Error("Conta não encontrada.");
    return apiFetch(`/api/v1/accounts/${account.id}/reference`, { method: "POST", body: JSON.stringify({ reference_date: input.date, reference_balance_minor: input.balance, expected_revision: account.revision, reason: input.reason, preview_token: result.preview_token }) });
  }, onSuccess: () => { setReferencePreview(null); referenceForm.reset(); refresh(); }, onError: (error) => { if (error instanceof ApiError && error.code === "STALE_PREVIEW" && error.detail?.preview) setReferencePreview((current) => current ? { input: current.input, result: error.detail?.preview as ReferencePreview } : null); } });
  return <Page eyebrow="Saldos conciliáveis" title="Contas" description="O saldo de referência representa o início da data escolhida.">
    <div className="account-grid"><section className="panel wide"><div className="panel-heading"><h2>Saldos atuais</h2><span>Limite de cartão não incluído</span></div><AsyncState loading={accounts.isPending} error={accounts.isError} empty={accounts.data?.total === 0}><div className="account-cards">{accounts.data?.items.map((account) => <article key={account.id}><small>{account.institution || "Conta"}</small><h3>{account.name}</h3><strong>{formatBrl(account.current_balance_minor)}</strong><p>Referência {formatDateBr(account.reference_date)}: {formatBrl(account.reference_balance_minor)}</p><div className="button-row"><button className="text-button" onClick={() => { setEditing(account); setEditName(account.name); }}>Renomear</button><button className="text-button danger-text" onClick={() => { if (window.confirm(`Arquivar ${account.name}? O histórico e as obrigações continuarão visíveis.`)) archive.mutate(account); }}>Arquivar</button></div></article>)}</div></AsyncState></section>
      <form className="panel form-panel" onSubmit={accountForm.handleSubmit((v) => add.mutate(accountSchema.parse(v)))}><h2>Nova conta</h2><label className="field"><span>Nome</span><input {...accountForm.register("name")} /></label><label className="field"><span>Instituição</span><input {...accountForm.register("institution")} /></label><MoneyField label="Saldo inicial da data" registration={accountForm.register("balance")} error={accountForm.formState.errors.balance} /><label className="field"><span>Data de referência</span><input type="date" {...accountForm.register("referenceDate")} /></label><p className="hint">Movimentos efetivados nesta data serão aplicados ao saldo.</p><button className="primary">Adicionar conta</button></form>
      <form className="panel form-panel" onSubmit={transferForm.handleSubmit((v) => requestTransfer.mutate(transferSchema.parse(v)))}><h2>Transferir</h2><label className="field"><span>Origem</span><select {...transferForm.register("from")}><option value="">Selecione</option>{accounts.data?.items.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="field"><span>Destino</span><select {...transferForm.register("to")}><option value="">Selecione</option>{accounts.data?.items.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label><MoneyField label="Valor" registration={transferForm.register("amount")} error={transferForm.formState.errors.amount} /><label className="field"><span>Data</span><input type="date" {...transferForm.register("date")} /></label><button className="secondary">Revisar transferência</button></form>
    </div>
    <details className="panel compact"><summary>Corrigir saldo/data de referência</summary><form className="inline-form" onSubmit={referenceForm.handleSubmit((value) => requestReference.mutate(referenceSchema.parse(value)))}><label className="field"><span>Conta</span><select {...referenceForm.register("accountId")}><option value="">Selecione</option>{accounts.data?.items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><MoneyField label="Novo saldo de referência" registration={referenceForm.register("balance")} error={referenceForm.formState.errors.balance} /><label className="field"><span>Nova data de referência</span><input type="date" {...referenceForm.register("date")} /></label><label className="field"><span>Justificativa</span><input {...referenceForm.register("reason")} /></label><button className="secondary">Revisar efeito</button></form></details>
    {preview && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><h2>Confirmar transferência</h2><p>Valor: <strong>{formatBrl(preview.result.amount_minor)}</strong></p><p>Saldo da origem após: {formatBrl(preview.result.source_balance_after_minor)} · saldo do destino após: {formatBrl(preview.result.target_balance_after_minor)}.</p><p>Variação consolidada: {formatBrl(preview.result.consolidated_change_minor)}. Não é receita nem despesa.</p><div className="modal-actions"><button className="ghost" onClick={() => setPreview(null)}>Voltar</button><button className="primary" onClick={() => transfer.mutate(preview)}>Confirmar gravação atômica</button></div></section></div>}
    {editing && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><h2>Renomear conta</h2><label className="field"><span>Novo nome</span><input value={editName} onChange={(event) => setEditName(event.target.value)} /></label><div className="modal-actions"><button className="ghost" onClick={() => setEditing(null)}>Cancelar</button><button className="primary" disabled={!editName.trim()} onClick={() => rename.mutate(editing)}>Salvar correção</button></div></section></div>}
    {referencePreview && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><h2>Confirmar nova referência</h2><p>Saldo atual calculado: {formatBrl(referencePreview.result.current_balance_before_minor)}. Após a correção: {formatBrl(referencePreview.result.current_balance_after_minor)}.</p><p>Diferença: {formatBrl(referencePreview.result.difference_minor)} · {referencePreview.result.covered_movement_count} movimento(s) desta data em diante serão somados. A alteração ficará auditada.</p><div className="modal-actions"><button className="ghost" onClick={() => setReferencePreview(null)}>Voltar</button><button className="primary" onClick={() => confirmReference.mutate(referencePreview)}>Confirmar correção</button></div></section></div>}
  </Page>;
}
