import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { apiFetch, idempotencyHeaders } from "../api/client";
import type { CashEntry, Page as PageType } from "../api/types";
import { AsyncState } from "../components/AsyncState";
import { MoneyField } from "../components/MoneyField";
import { Page } from "../components/Page";
import { useAccounts, useCategories } from "../hooks/useFinanceData";
import { formatDateBr } from "../lib/dates";
import { moneyText, requiredText, todayIso } from "../lib/forms";
import { formatBrl, parseBrlToMinor } from "../lib/money";

const schema = z.object({ accountId: requiredText, categoryId: z.string(), kind: z.enum(["income", "expense"]), description: requiredText, amount: moneyText, plannedDate: z.string(), status: z.enum(["planned", "effective"]), note: z.string() });
type Values = z.input<typeof schema>;

export function MovementsPage() {
  const queryClient = useQueryClient();
  const accounts = useAccounts();
  const categories = useCategories();
  const [pageNumber, setPageNumber] = useState(1);
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("");
  const [accountFilter, setAccountFilter] = useState("");
  const [editing, setEditing] = useState<CashEntry | null>(null);
  const [editDescription, setEditDescription] = useState("");
  const [editAmount, setEditAmount] = useState("");
  const [editReason, setEditReason] = useState("");
  const params = new URLSearchParams({ page: String(pageNumber), page_size: "25" });
  if (search) params.set("search", search);
  if (status) params.set("status", status);
  if (accountFilter) params.set("account_id", accountFilter);
  const entries = useQuery({ queryKey: ["cash-entries", pageNumber, search, status, accountFilter], queryFn: () => apiFetch<PageType<CashEntry>>(`/api/v1/cash-entries?${params}`) });
  const form = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { accountId: "", categoryId: "", kind: "expense", description: "", amount: "", plannedDate: todayIso(), status: "effective", note: "" } });
  const refresh = () => { void queryClient.invalidateQueries({ queryKey: ["cash-entries"] }); void queryClient.invalidateQueries({ queryKey: ["monthly"] }); void queryClient.invalidateQueries({ queryKey: ["accounts"] }); };
  const save = useMutation({ mutationFn: (value: z.output<typeof schema>) => apiFetch("/api/v1/cash-entries", { method: "POST", headers: idempotencyHeaders(), body: JSON.stringify({ account_id: value.accountId, category_id: value.categoryId || null, kind: value.kind, description: value.description, amount_minor: value.amount, planned_date: value.plannedDate, effective_date: value.status === "effective" ? value.plannedDate : null, status: value.status, note: value.note || null }) }), onSuccess: () => { form.reset(); refresh(); } });
  const transition = useMutation({ mutationFn: ({ entry, target }: { entry: CashEntry; target: "effective" | "cancelled" | "voided" }) => apiFetch(`/api/v1/cash-entries/${entry.id}/${target}`, { method: "POST", body: JSON.stringify({ expected_revision: entry.revision, effective_date: target === "effective" ? todayIso() : null, reason: target === "effective" ? null : "Ação confirmada pelo usuário" }) }), onSuccess: refresh });
  const correct = useMutation({ mutationFn: (entry: CashEntry) => apiFetch(`/api/v1/cash-entries/${entry.id}`, { method: "PUT", body: JSON.stringify({ account_id: entry.account_id, category_id: entry.category_id, kind: entry.kind, description: editDescription, amount_minor: parseBrlToMinor(editAmount), planned_date: entry.planned_date, effective_date: entry.effective_date, status: entry.status, note: null, expected_revision: entry.revision, reason: editReason }) }), onSuccess: () => { setEditing(null); refresh(); } });
  const kind = form.watch("kind");
  return <Page eyebrow="Caixa e previsões" title="Movimentações" description="Efetivado altera caixa; previsto aguarda sua confirmação.">
    <div className="grid-form"><form className="panel form-panel" onSubmit={form.handleSubmit((value) => save.mutate(schema.parse(value)))}><h2>Novo lançamento</h2><label className="field"><span>Tipo</span><select {...form.register("kind")}><option value="expense">Despesa</option><option value="income">Receita</option></select></label><label className="field"><span>Descrição</span><input {...form.register("description")} />{form.formState.errors.description && <small className="field-error">{form.formState.errors.description.message}</small>}</label><MoneyField label="Valor positivo" registration={form.register("amount")} error={form.formState.errors.amount} /><label className="field"><span>Conta</span><select {...form.register("accountId")}><option value="">Selecione</option>{accounts.data?.items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="field"><span>Categoria (opcional)</span><select {...form.register("categoryId")}><option value="">Sem categoria</option>{categories.data?.items.filter((item) => item.kind === kind).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="field-row"><label className="field"><span>Data</span><input type="date" {...form.register("plannedDate")} /></label><label className="field"><span>Estado</span><select {...form.register("status")}><option value="effective">Efetivado</option><option value="planned">Previsto</option></select></label></div><label className="field"><span>Observação (opcional)</span><textarea {...form.register("note")} /></label>{save.isError && <p className="field-error" role="alert">Não foi possível salvar.</p>}<button className="primary" disabled={save.isPending}>Salvar movimentação</button></form>
      <section className="panel"><div className="panel-heading"><h2>Histórico e origem</h2><span>{entries.data?.total ?? 0} registros</span></div><div className="filters"><label className="field"><span>Buscar</span><input value={search} onChange={(event) => { setSearch(event.target.value); setPageNumber(1); }} /></label><label className="field"><span>Conta</span><select value={accountFilter} onChange={(event) => { setAccountFilter(event.target.value); setPageNumber(1); }}><option value="">Todas</option>{accounts.data?.items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="field"><span>Estado</span><select value={status} onChange={(event) => { setStatus(event.target.value); setPageNumber(1); }}><option value="">Todos</option><option value="planned">Previsto</option><option value="effective">Efetivado</option><option value="cancelled">Cancelado</option><option value="voided">Anulado</option></select></label></div><AsyncState loading={entries.isPending} error={entries.isError} empty={entries.data?.total === 0}><div className="list">{entries.data?.items.map((entry) => <article className="list-row" key={entry.id}><div><strong>{entry.description}</strong><small>{formatDateBr(entry.effective_date ?? entry.planned_date)} · {entry.status} · origem {entry.source}</small></div><div className="invoice-action"><span className={entry.signed_amount_minor < 0 ? "negative" : "positive"}>{formatBrl(entry.signed_amount_minor)}</span>{entry.source === "manual" && <button className="text-button" onClick={() => { setEditing(entry); setEditDescription(entry.description); setEditAmount((Math.abs(entry.signed_amount_minor) / 100).toFixed(2).replace(".", ",")); setEditReason(""); }}>Corrigir</button>}{entry.status === "planned" && <button className="text-button" onClick={() => { if (window.confirm("Confirmar este previsto como efetivado hoje?")) transition.mutate({ entry, target: "effective" }); }}>Confirmar</button>}{entry.status === "planned" && <button className="text-button danger-text" onClick={() => { if (window.confirm("Cancelar esta previsão? O registro continuará no histórico.")) transition.mutate({ entry, target: "cancelled" }); }}>Cancelar</button>}{entry.status === "effective" && entry.source === "manual" && <button className="text-button danger-text" onClick={() => { if (window.confirm("Anular o lançamento? Use somente para erro; estorno real deve ser registrado separadamente.")) transition.mutate({ entry, target: "voided" }); }}>Anular erro</button>}</div></article>)}</div><div className="pagination"><button disabled={pageNumber === 1} onClick={() => setPageNumber((value) => value - 1)}>Anterior</button><span>Página {pageNumber}</span><button disabled={!entries.data || pageNumber * entries.data.page_size >= entries.data.total} onClick={() => setPageNumber((value) => value + 1)}>Próxima</button></div></AsyncState></section>
    </div>
    {editing && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><h2>Corrigir movimentação</h2><p>A alteração guarda antes/depois na auditoria. Cancelamento e estorno têm fluxos próprios.</p><label className="field"><span>Descrição</span><input value={editDescription} onChange={(event) => setEditDescription(event.target.value)} /></label><label className="field"><span>Valor positivo</span><input inputMode="decimal" value={editAmount} onChange={(event) => setEditAmount(event.target.value)} /></label><label className="field"><span>Justificativa</span><textarea value={editReason} onChange={(event) => setEditReason(event.target.value)} /></label>{correct.isError && <p className="field-error">Confira o valor e a justificativa.</p>}<div className="modal-actions"><button className="ghost" onClick={() => setEditing(null)}>Cancelar</button><button className="primary" disabled={!editReason.trim()} onClick={() => correct.mutate(editing)}>Salvar correção</button></div></section></div>}
  </Page>;
}
