import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { ApiError, apiFetch, idempotencyHeaders } from "../api/client";
import { AsyncState } from "../components/AsyncState";
import { MoneyField } from "../components/MoneyField";
import { Page } from "../components/Page";
import { useAccounts, useCards, useCategories, useInvoices } from "../hooks/useFinanceData";
import { formatDateBr, formatMonthBr } from "../lib/dates";
import { currentMonth, moneyText, requiredText, todayIso } from "../lib/forms";
import { formatBrl } from "../lib/money";

const plannedSchema = z.object({ cardId: requiredText, categoryId: z.string(), description: requiredText, expectedDate: z.string(), amount: moneyText, invoiceMonth: z.string() });
const confirmationSchema = z.object({ purchaseDate: z.string(), total: moneyText, count: z.coerce.number().int().min(1), firstMonth: z.string() });
const recurrenceSchema = z.object({ kind: z.enum(["income", "expense", "card_purchase"]), description: requiredText, accountId: z.string(), cardId: z.string(), categoryId: z.string(), amount: moneyText, day: z.coerce.number().int().min(1).max(31), startMonth: z.string(), endMonth: z.string() });
const planSchema = z.object({ invoiceId: requiredText, accountId: requiredText, plannedDate: z.string() });

type Projection = { current_minor: number; projected_minor: number; incomplete_by_account: boolean; items: { key: string; date: string; signed_amount_minor: number; source: string; account_id: string | null }[] };
type Planned = { id: string; card_id: string; category_id: string | null; description: string; expected_date: string; expected_amount_minor: number; estimated_invoice_month: string; status: string; revision: number; dependency_warning?: string | null };
type PurchasePreview = { preview_token: string; total_minor: number; schedule: { installment_number: number; amount_minor: number; reference_month: string; due_date: string }[] };
type Recurrences = { rules: { id: string; description: string; amount_minor: number; day: number; active: number; dependency_warning?: string | null }[]; occurrences: { id: string; occurrence_month: string; expected_date: string; expected_amount_minor: number; status: string }[] };
type Plan = { id: string; invoice_id: string; account_id: string; planned_date: string; status: string; revision: number };

export function PlanningPage() {
  const cards = useCards();
  const accounts = useAccounts();
  const categories = useCategories();
  const invoices = useInvoices();
  const queryClient = useQueryClient();
  const through = `${Number(currentMonth().slice(0, 4)) + 1}-${currentMonth().slice(5)}`;
  const projection = useQuery({ queryKey: ["projection"], queryFn: () => apiFetch<Projection>(`/api/v1/reports/projection?through_month=${through}`) });
  const planned = useQuery({ queryKey: ["planned-purchases"], queryFn: () => apiFetch<{ items: Planned[] }>("/api/v1/planned-purchases?status=planned") });
  const recurrences = useQuery({ queryKey: ["recurrences"], queryFn: () => apiFetch<Recurrences>("/api/v1/recurrences") });
  const plans = useQuery({ queryKey: ["payment-plans"], queryFn: () => apiFetch<{ items: Plan[] }>("/api/v1/invoice-payment-plans") });
  const [selectedPlanned, setSelectedPlanned] = useState<Planned | null>(null);
  const [purchasePreview, setPurchasePreview] = useState<PurchasePreview | null>(null);
  const [occurrencePreview, setOccurrencePreview] = useState<Recurrences["occurrences"][number] | null>(null);
  const [notice, setNotice] = useState("");

  const refresh = () => {
    for (const key of [["projection"], ["planned-purchases"], ["recurrences"], ["payment-plans"], ["invoices"], ["cards"]]) void queryClient.invalidateQueries({ queryKey: key });
  };
  const form = useForm<z.input<typeof plannedSchema>>({ resolver: zodResolver(plannedSchema), defaultValues: { cardId: "", categoryId: "", description: "", expectedDate: todayIso(), amount: "", invoiceMonth: currentMonth() } });
  const confirmation = useForm<z.input<typeof confirmationSchema>>({ resolver: zodResolver(confirmationSchema), defaultValues: { purchaseDate: todayIso(), total: "", count: 1, firstMonth: currentMonth() } });
  const recurrence = useForm<z.input<typeof recurrenceSchema>>({ resolver: zodResolver(recurrenceSchema), defaultValues: { kind: "expense", description: "", accountId: "", cardId: "", categoryId: "", amount: "", day: new Date().getDate(), startMonth: currentMonth(), endMonth: "" } });
  const paymentPlan = useForm<z.input<typeof planSchema>>({ resolver: zodResolver(planSchema), defaultValues: { invoiceId: "", accountId: "", plannedDate: todayIso() } });

  const save = useMutation({ mutationFn: (v: z.output<typeof plannedSchema>) => apiFetch("/api/v1/planned-purchases", { method: "POST", body: JSON.stringify({ card_id: v.cardId, category_id: v.categoryId || null, description: v.description, expected_date: v.expectedDate, expected_amount_minor: v.amount, estimated_invoice_month: v.invoiceMonth }) }), onSuccess: () => { form.reset(); refresh(); } });
  const previewConfirmation = useMutation({ mutationFn: async (v: z.output<typeof confirmationSchema>) => {
    if (!selectedPlanned) throw new Error("Selecione uma previsão.");
    return apiFetch<PurchasePreview>(`/api/v1/planned-purchases/${selectedPlanned.id}/preview-confirmation`, { method: "POST", body: JSON.stringify({ card_id: selectedPlanned.card_id, category_id: selectedPlanned.category_id, description: selectedPlanned.description, purchase_date: v.purchaseDate, total_minor: v.total, installment_count: v.count, first_invoice_month: v.firstMonth }) });
  }, onSuccess: setPurchasePreview });
  const confirmPurchase = useMutation({ mutationFn: (v: z.output<typeof confirmationSchema>) => {
    if (!selectedPlanned || !purchasePreview) throw new Error("Prévia ausente.");
    return apiFetch(`/api/v1/planned-purchases/${selectedPlanned.id}/confirm`, { method: "POST", headers: idempotencyHeaders(), body: JSON.stringify({ purchase_date: v.purchaseDate, total_minor: v.total, installment_count: v.count, first_invoice_month: v.firstMonth, preview_token: purchasePreview.preview_token }) });
  }, onSuccess: () => { setSelectedPlanned(null); setPurchasePreview(null); refresh(); }, onError: (error) => { if (error instanceof ApiError && error.code === "STALE_PREVIEW" && error.detail?.preview) { setPurchasePreview(error.detail.preview as PurchasePreview); setNotice("A prévia mudou. Revise o novo cronograma."); } } });
  const cancelPlanned = useMutation({ mutationFn: (item: Planned) => apiFetch(`/api/v1/planned-purchases/${item.id}/cancel`, { method: "POST", body: JSON.stringify({ expected_revision: item.revision, reason: "Cancelado pelo usuário após confirmação" }) }), onSuccess: refresh });
  const saveRecurrence = useMutation({ mutationFn: (v: z.output<typeof recurrenceSchema>) => apiFetch("/api/v1/recurrences", { method: "POST", body: JSON.stringify({ kind: v.kind, description: v.description, account_id: v.kind === "card_purchase" ? null : v.accountId, card_id: v.kind === "card_purchase" ? v.cardId : null, category_id: v.categoryId || null, amount_minor: v.amount, day: v.day, start_month: v.startMonth, end_month: v.endMonth || null }) }), onSuccess: () => { recurrence.reset(); refresh(); } });
  const confirmOccurrence = useMutation({ mutationFn: (item: Recurrences["occurrences"][number]) => apiFetch(`/api/v1/recurrence-occurrences/${item.id}/confirm`, { method: "POST", headers: idempotencyHeaders(), body: JSON.stringify({ actual_date: item.expected_date > todayIso() ? todayIso() : item.expected_date, actual_amount_minor: item.expected_amount_minor }) }), onSuccess: () => { setOccurrencePreview(null); refresh(); } });
  const createPlan = useMutation({ mutationFn: (v: z.output<typeof planSchema>) => apiFetch(`/api/v1/invoices/${v.invoiceId}/payment-plan`, { method: "POST", body: JSON.stringify({ account_id: v.accountId, planned_date: v.plannedDate }) }), onSuccess: () => { paymentPlan.reset(); refresh(); } });

  const recurrenceKind = recurrence.watch("kind");
  return <Page eyebrow="Horizonte de 12 meses" title="Planejamento" description="Previsões vencidas mantêm a data original e nunca são confirmadas automaticamente.">
    <section className="metrics"><article className="metric featured"><span>Saldo confirmado atual</span><strong>{formatBrl(projection.data?.current_minor ?? 0)}</strong></article><article className="metric"><span>Saldo ao fim do horizonte</span><strong>{formatBrl(projection.data?.projected_minor ?? 0)}</strong><small>{projection.data?.incomplete_by_account ? "Há obrigação sem conta definida" : "Contas atribuídas"}</small></article></section>
    <div className="grid-form"><form className="panel form-panel" onSubmit={form.handleSubmit((v) => save.mutate(plannedSchema.parse(v)))}><h2>Compra futura planejada</h2><p className="hint">Previsto: não cria compra, parcela ou débito confirmado.</p><label className="field"><span>Descrição</span><input {...form.register("description")} /></label><label className="field"><span>Cartão</span><select {...form.register("cardId")}><option value="">Selecione</option>{cards.data?.items.map((c) => <option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label className="field"><span>Categoria</span><select {...form.register("categoryId")}><option value="">Sem categoria</option>{categories.data?.items.filter((c) => c.kind === "expense").map((c) => <option value={c.id} key={c.id}>{c.name}</option>)}</select></label><MoneyField label="Valor esperado" registration={form.register("amount")} error={form.formState.errors.amount} /><div className="field-row"><label className="field"><span>Data esperada</span><input type="date" {...form.register("expectedDate")} /></label><label className="field"><span>Fatura estimada</span><input type="month" {...form.register("invoiceMonth")} /></label></div><button className="primary">Salvar previsão</button></form>
      <section className="panel"><div className="panel-heading"><h2>Compras previstas</h2><span>{planned.data?.items.length ?? 0} pendentes</span></div><AsyncState loading={planned.isPending} error={planned.isError} empty={!planned.data?.items.length}><div className="list">{planned.data?.items.map((item) => <article className="list-row" key={item.id}><div><strong>{item.description}</strong><small>Previsto {formatDateBr(item.expected_date)} · fatura {formatMonthBr(item.estimated_invoice_month)}</small></div><div className="invoice-action"><span>{formatBrl(item.expected_amount_minor)}</span><button className="text-button" onClick={() => { setSelectedPlanned(item); setPurchasePreview(null); confirmation.reset({ purchaseDate: item.expected_date > todayIso() ? todayIso() : item.expected_date, total: (item.expected_amount_minor / 100).toFixed(2).replace(".", ","), count: 1, firstMonth: item.estimated_invoice_month }); }}>Confirmar compra</button><button className="text-button danger-text" onClick={() => { if (window.confirm(`Cancelar a previsão ${item.description}? Ela deixará de contar no planejamento.`)) cancelPlanned.mutate(item); }}>Cancelar</button></div></article>)}</div></AsyncState></section>
    </div>
    <section className="panel"><div className="panel-heading"><h2>Linha do tempo</h2><span>Cada obrigação uma vez</span></div><AsyncState loading={projection.isPending} error={projection.isError} empty={!projection.data?.items.length}><div className="timeline">{projection.data?.items.map((item) => <article key={item.key}><time>{formatDateBr(item.date)}</time><div><strong>{item.source === "cash_entry" ? "Movimentação prevista" : "Pagamento projetado de fatura"}</strong><small>{item.account_id ? "Conta atribuída" : "Sem conta — projeção por conta incompleta"}</small></div><span>{formatBrl(item.signed_amount_minor)}</span></article>)}</div></AsyncState></section>
    <div className="grid-form"><form className="panel form-panel" onSubmit={recurrence.handleSubmit((v) => saveRecurrence.mutate(recurrenceSchema.parse(v)))}><h2>Nova recorrência mensal</h2><label className="field"><span>Tipo</span><select {...recurrence.register("kind")}><option value="expense">Despesa em conta</option><option value="income">Receita em conta</option><option value="card_purchase">Compra no cartão (1 parcela)</option></select></label><label className="field"><span>Descrição</span><input {...recurrence.register("description")} /></label><MoneyField label="Valor esperado" registration={recurrence.register("amount")} error={recurrence.formState.errors.amount} />{recurrenceKind === "card_purchase" ? <label className="field"><span>Cartão</span><select {...recurrence.register("cardId")}><option value="">Selecione</option>{cards.data?.items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label> : <label className="field"><span>Conta</span><select {...recurrence.register("accountId")}><option value="">Selecione</option>{accounts.data?.items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<label className="field"><span>Categoria</span><select {...recurrence.register("categoryId")}><option value="">Sem categoria</option>{categories.data?.items.filter((item) => item.kind === (recurrenceKind === "income" ? "income" : "expense")).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="field-row"><label className="field"><span>Dia original</span><input type="number" min="1" max="31" {...recurrence.register("day")} /></label><label className="field"><span>Início</span><input type="month" {...recurrence.register("startMonth")} /></label></div><label className="field"><span>Fim (opcional)</span><input type="month" {...recurrence.register("endMonth")} /></label><button className="primary">Criar e gerar 12 meses</button></form>
      <section className="panel"><div className="panel-heading"><h2>Ocorrências pendentes</h2><span>Confirmação manual</span></div><AsyncState loading={recurrences.isPending} error={recurrences.isError} empty={!recurrences.data?.occurrences.some((item) => item.status === "planned")}><div className="list">{recurrences.data?.occurrences.filter((item) => item.status === "planned").slice(0, 20).map((item) => <article className="list-row" key={item.id}><div><strong>{formatMonthBr(item.occurrence_month)}</strong><small>{formatDateBr(item.expected_date)} · Previsto</small></div><div className="invoice-action"><span>{formatBrl(item.expected_amount_minor)}</span><button className="text-button" onClick={() => setOccurrencePreview(item)}>Revisar confirmação</button></div></article>)}</div></AsyncState></section>
    </div>
    <div className="grid-form"><form className="panel form-panel" onSubmit={paymentPlan.handleSubmit((v) => createPlan.mutate(planSchema.parse(v)))}><h2>Planejar pagamento de fatura</h2><p className="hint">Conta e data são planejadas; o valor continua derivado da fatura e substitui a obrigação automática.</p><label className="field"><span>Fatura</span><select {...paymentPlan.register("invoiceId")}><option value="">Selecione</option>{invoices.data?.items.filter((item) => item.state !== "settled").map((item) => <option value={item.id} key={item.id}>{formatMonthBr(item.reference_month)} · {formatBrl(item.payable_minor)}</option>)}</select></label><label className="field"><span>Conta planejada</span><select {...paymentPlan.register("accountId")}><option value="">Selecione</option>{accounts.data?.items.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="field"><span>Data planejada</span><input type="date" {...paymentPlan.register("plannedDate")} /></label><button className="primary">Salvar plano</button></form><section className="panel"><h2>Planos de pagamento</h2><AsyncState loading={plans.isPending} error={plans.isError} empty={!plans.data?.items.some((item) => item.status === "active")}><div className="list">{plans.data?.items.filter((item) => item.status === "active").map((item) => <article className="list-row" key={item.id}><div><strong>Fatura {invoices.data?.items.find((invoice) => invoice.id === item.invoice_id)?.reference_month ?? item.invoice_id}</strong><small>{formatDateBr(item.planned_date)} · valor derivado, não duplicado</small></div></article>)}</div></AsyncState></section></div>
    {selectedPlanned && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><h2>Confirmar compra prevista</h2><form onSubmit={confirmation.handleSubmit((v) => purchasePreview ? confirmPurchase.mutate(confirmationSchema.parse(v)) : previewConfirmation.mutate(confirmationSchema.parse(v)))}><div className="field-row"><label className="field"><span>Data real</span><input type="date" max={todayIso()} {...confirmation.register("purchaseDate")} /></label><label className="field"><span>Parcelas reais</span><input type="number" min="1" {...confirmation.register("count")} /></label></div><MoneyField label="Valor real" registration={confirmation.register("total")} error={confirmation.formState.errors.total} /><label className="field"><span>Primeira fatura real</span><input type="month" {...confirmation.register("firstMonth")} /></label>{purchasePreview && <><p className="hint">A previsão de {formatBrl(selectedPlanned.expected_amount_minor)} será substituída atomicamente pela compra de {formatBrl(purchasePreview.total_minor)}.</p><table><thead><tr><th>Parcela</th><th>Fatura</th><th>Valor</th></tr></thead><tbody>{purchasePreview.schedule.map((item) => <tr key={item.installment_number}><td>{item.installment_number}</td><td>{formatMonthBr(item.reference_month)}</td><td>{formatBrl(item.amount_minor)}</td></tr>)}</tbody></table></>}{notice && <p className="field-error">{notice}</p>}<div className="modal-actions"><button type="button" className="ghost" onClick={() => { setSelectedPlanned(null); setPurchasePreview(null); }}>Voltar</button><button className="primary">{purchasePreview ? "Confirmar substituição" : "Gerar prévia"}</button></div></form></section></div>}
    {occurrencePreview && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><h2>Confirmar ocorrência?</h2><p>{formatDateBr(occurrencePreview.expected_date)} · {formatBrl(occurrencePreview.expected_amount_minor)}. A previsão será vinculada ao registro efetivo, sem duplicação.</p><div className="modal-actions"><button className="ghost" onClick={() => setOccurrencePreview(null)}>Voltar</button><button className="primary" onClick={() => confirmOccurrence.mutate(occurrencePreview)}>Confirmar como efetiva</button></div></section></div>}
  </Page>;
}
