import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { apiFetch } from "../api/client";
import { MoneyField } from "../components/MoneyField";
import { useAccounts, useCards, useCategories } from "../hooks/useFinanceData";
import { currentMonth, moneyText, requiredText, todayIso } from "../lib/forms";

const accountSchema = z.object({ name: requiredText, institution: z.string(), referenceDate: z.string().min(1, "Informe a data."), balance: moneyText });
const cardSchema = z.object({ name: requiredText, limit: moneyText, closingDay: z.coerce.number().int().min(1).max(31), dueDay: z.coerce.number().int().min(1).max(31), accountId: z.string() });
const categorySchema = z.object({ name: requiredText, kind: z.enum(["expense", "income"]) });
const recurrenceSchema = z.object({
  kind: z.enum(["income", "expense", "card_purchase"]), description: requiredText,
  accountId: z.string(), cardId: z.string(), categoryId: z.string(), amount: moneyText,
  day: z.coerce.number().int().min(1).max(31), startMonth: z.string().min(1, "Informe o mês."), endMonth: z.string(),
}).superRefine((value, context) => {
  if (value.kind === "card_purchase" && !value.cardId) context.addIssue({ code: z.ZodIssueCode.custom, path: ["cardId"], message: "Selecione um cartão." });
  if (value.kind !== "card_purchase" && !value.accountId) context.addIssue({ code: z.ZodIssueCode.custom, path: ["accountId"], message: "Selecione uma conta." });
});
const budgetSchema = z.object({ categoryId: requiredText, amount: moneyText, month: z.string().min(1, "Informe o mês."), asDefault: z.boolean() });

type AccountValues = z.input<typeof accountSchema>;
type CardValues = z.input<typeof cardSchema>;
type CategoryValues = z.input<typeof categorySchema>;
type RecurrenceValues = z.input<typeof recurrenceSchema>;
type BudgetValues = z.input<typeof budgetSchema>;

function StepActions({ pending, advance }: { pending: boolean; advance: () => void }) {
  return <div className="button-row setup-actions"><button type="button" className="secondary" disabled={pending} onClick={advance}>Configurar depois</button><button type="button" className="primary" disabled={pending} onClick={advance}>Continuar</button></div>;
}

export function SetupPage({ initialStep }: { initialStep: number }) {
  const [step, setStep] = useState(initialStep);
  const queryClient = useQueryClient();
  const status = useQuery({ queryKey: ["status"], queryFn: () => apiFetch<{ data_directory: string }>("/api/v1/status") });
  const accounts = useAccounts();
  const cards = useCards();
  const categories = useCategories();
  const accountForm = useForm<AccountValues>({ resolver: zodResolver(accountSchema), defaultValues: { name: "", institution: "", referenceDate: todayIso(), balance: "0,00" } });
  const cardForm = useForm<CardValues>({ resolver: zodResolver(cardSchema), defaultValues: { name: "", limit: "", closingDay: 10, dueDay: 20, accountId: "" } });
  const categoryForm = useForm<CategoryValues>({ resolver: zodResolver(categorySchema), defaultValues: { name: "", kind: "expense" } });
  const recurrenceForm = useForm<RecurrenceValues>({ resolver: zodResolver(recurrenceSchema), defaultValues: { kind: "expense", description: "", accountId: "", cardId: "", categoryId: "", amount: "", day: new Date().getDate(), startMonth: currentMonth(), endMonth: "" } });
  const budgetForm = useForm<BudgetValues>({ resolver: zodResolver(budgetSchema), defaultValues: { categoryId: "", amount: "", month: currentMonth(), asDefault: true } });

  const persistStep = useMutation({ mutationFn: (next: number) => apiFetch("/api/v1/setup", { method: "PUT", body: JSON.stringify({ setup_step: next }) }), onSuccess: (_data, next) => { setStep(next); if (next === 8) void queryClient.invalidateQueries({ queryKey: ["setup"] }); } });
  const advance = () => persistStep.mutate(step + 1);
  const saveAccount = useMutation({ mutationFn: (v: z.output<typeof accountSchema>) => apiFetch("/api/v1/accounts", { method: "POST", body: JSON.stringify({ name: v.name, institution: v.institution || null, reference_date: v.referenceDate, reference_balance_minor: v.balance }) }), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["accounts"] }); persistStep.mutate(2); } });
  const saveCard = useMutation({ mutationFn: (v: z.output<typeof cardSchema>) => apiFetch("/api/v1/cards", { method: "POST", body: JSON.stringify({ name: v.name, limit_minor: v.limit, closing_day: v.closingDay, due_day: v.dueDay, default_account_id: v.accountId || null }) }), onSuccess: () => { cardForm.reset({ name: "", limit: "", closingDay: 10, dueDay: 20, accountId: "" }); void queryClient.invalidateQueries({ queryKey: ["cards"] }); } });
  const saveCategory = useMutation({ mutationFn: (v: z.output<typeof categorySchema>) => apiFetch("/api/v1/categories", { method: "POST", body: JSON.stringify(v) }), onSuccess: () => { categoryForm.reset({ name: "", kind: "expense" }); void queryClient.invalidateQueries({ queryKey: ["categories"] }); } });
  const saveRecurrence = useMutation({ mutationFn: (v: z.output<typeof recurrenceSchema>) => apiFetch("/api/v1/recurrences", { method: "POST", body: JSON.stringify({ kind: v.kind, description: v.description, account_id: v.kind === "card_purchase" ? null : v.accountId, card_id: v.kind === "card_purchase" ? v.cardId : null, category_id: v.categoryId || null, amount_minor: v.amount, day: v.day, start_month: v.startMonth, end_month: v.endMonth || null }) }), onSuccess: () => recurrenceForm.reset({ kind: "expense", description: "", accountId: "", cardId: "", categoryId: "", amount: "", day: new Date().getDate(), startMonth: currentMonth(), endMonth: "" }) });
  const saveBudget = useMutation({ mutationFn: (v: z.output<typeof budgetSchema>) => apiFetch(v.asDefault ? "/api/v1/budget-defaults" : "/api/v1/budgets", { method: "POST", body: JSON.stringify(v.asDefault ? { category_id: v.categoryId, effective_from_month: v.month, amount_minor: v.amount } : { category_id: v.categoryId, month: v.month, amount_minor: v.amount }) }), onSuccess: () => budgetForm.reset({ categoryId: "", amount: "", month: currentMonth(), asDefault: true }) });

  if (step === 0) return <main className="setup"><p className="eyebrow">Primeiro acesso · 1 de 8</p><h1>Seu dinheiro, no seu computador.</h1><p>O assistente ajudará a configurar sua conta, cartões, categorias, planejamento e orçamentos. Todas as etapas opcionais podem ser puladas.</p><div className="setup-facts"><div><strong>Local</strong><span>Banco e backups ficam em {status.data?.data_directory ?? "sua pasta de perfil"}.</span></div><div><strong>Manual</strong><span>Você confirma cada previsão.</span></div><div><strong>Privado</strong><span>Nenhum dado é enviado a mantenedores.</span></div></div><button className="primary" onClick={() => setStep(1)}>Começar configuração</button></main>;

  if (step === 1) return <main className="setup narrow"><p className="eyebrow">Etapa obrigatória · 2 de 8</p><h1>Cadastre sua primeira conta</h1><p>O saldo representa o início da data escolhida, antes dos movimentos registrados naquele dia.</p><form onSubmit={accountForm.handleSubmit((v) => saveAccount.mutate(accountSchema.parse(v)))}><label className="field"><span>Nome da conta</span><input {...accountForm.register("name")} />{accountForm.formState.errors.name && <small className="field-error">{accountForm.formState.errors.name.message}</small>}</label><label className="field"><span>Instituição (opcional)</span><input {...accountForm.register("institution")} /></label><MoneyField label="Saldo inicial da data" registration={accountForm.register("balance")} error={accountForm.formState.errors.balance} /><label className="field"><span>Data de referência</span><input type="date" {...accountForm.register("referenceDate")} />{accountForm.formState.errors.referenceDate && <small className="field-error">{accountForm.formState.errors.referenceDate.message}</small>}</label>{saveAccount.isError && <p role="alert" className="field-error">Não foi possível salvar a conta.</p>}<button className="primary" disabled={saveAccount.isPending}>{saveAccount.isPending ? "Salvando…" : "Salvar e continuar"}</button></form></main>;

  if (step === 2) return <main className="setup narrow"><p className="eyebrow">Etapa opcional · 3 de 8</p><h1>Configure seus cartões</h1><p>Cadastre quantos cartões quiser. Compras e faturas em aberto podem ser informadas depois na tela completa.</p><form onSubmit={cardForm.handleSubmit((v) => saveCard.mutate(cardSchema.parse(v)))}><label className="field"><span>Nome do cartão</span><input {...cardForm.register("name")} />{cardForm.formState.errors.name && <small className="field-error">{cardForm.formState.errors.name.message}</small>}</label><MoneyField label="Limite" registration={cardForm.register("limit")} error={cardForm.formState.errors.limit} /><div className="field-row"><label className="field"><span>Dia de fechamento</span><input type="number" min="1" max="31" {...cardForm.register("closingDay")} /></label><label className="field"><span>Dia de vencimento</span><input type="number" min="1" max="31" {...cardForm.register("dueDay")} /></label></div><label className="field"><span>Conta habitual para pagamento</span><select {...cardForm.register("accountId")}><option value="">Definir depois</option>{accounts.data?.items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{saveCard.isError && <p className="field-error" role="alert">Não foi possível salvar o cartão.</p>}<button className="primary" disabled={saveCard.isPending}>Adicionar cartão</button></form>{Boolean(cards.data?.items.length) && <p className="setup-saved" role="status">{cards.data?.items.length} cartão(ões) configurado(s).</p>}<StepActions pending={persistStep.isPending} advance={advance} /></main>;

  if (step === 3) return <main className="setup narrow"><p className="eyebrow">Etapa opcional · 4 de 8</p><h1>Crie suas categorias</h1><p>Cadastre categorias de despesas e receitas. Você pode adicionar várias antes de continuar.</p><form onSubmit={categoryForm.handleSubmit((v) => saveCategory.mutate(categorySchema.parse(v)))}><label className="field"><span>Nome da categoria</span><input {...categoryForm.register("name")} />{categoryForm.formState.errors.name && <small className="field-error">{categoryForm.formState.errors.name.message}</small>}</label><label className="field"><span>Tipo</span><select {...categoryForm.register("kind")}><option value="expense">Despesa</option><option value="income">Receita</option></select></label>{saveCategory.isError && <p className="field-error" role="alert">Não foi possível salvar a categoria.</p>}<button className="primary" disabled={saveCategory.isPending}>Adicionar categoria</button></form>{Boolean(categories.data?.items.length) && <div className="tag-list setup-list">{categories.data?.items.map((item) => <span key={item.id}>{item.name}<small>{item.kind === "expense" ? "Despesa" : "Receita"}</small></span>)}</div>}<StepActions pending={persistStep.isPending} advance={advance} /></main>;

  const recurrenceKind = recurrenceForm.watch("kind");
  if (step === 4) return <main className="setup narrow"><p className="eyebrow">Etapa opcional · 5 de 8</p><h1>Monte seu planejamento</h1><p>Adicione receitas, despesas ou compras mensais recorrentes. Elas serão previstas por 12 meses e nunca serão efetivadas automaticamente.</p><form onSubmit={recurrenceForm.handleSubmit((v) => saveRecurrence.mutate(recurrenceSchema.parse(v)))}><label className="field"><span>Tipo</span><select {...recurrenceForm.register("kind")}><option value="expense">Despesa em conta</option><option value="income">Receita em conta</option><option value="card_purchase">Compra no cartão</option></select></label><label className="field"><span>Descrição</span><input {...recurrenceForm.register("description")} /></label><MoneyField label="Valor esperado" registration={recurrenceForm.register("amount")} error={recurrenceForm.formState.errors.amount} />{recurrenceKind === "card_purchase" ? <label className="field"><span>Cartão</span><select {...recurrenceForm.register("cardId")}><option value="">Selecione</option>{cards.data?.items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>{recurrenceForm.formState.errors.cardId && <small className="field-error">{recurrenceForm.formState.errors.cardId.message}</small>}</label> : <label className="field"><span>Conta</span><select {...recurrenceForm.register("accountId")}><option value="">Selecione</option>{accounts.data?.items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>{recurrenceForm.formState.errors.accountId && <small className="field-error">{recurrenceForm.formState.errors.accountId.message}</small>}</label>}<label className="field"><span>Categoria (opcional)</span><select {...recurrenceForm.register("categoryId")}><option value="">Sem categoria</option>{categories.data?.items.filter((item) => item.kind === (recurrenceKind === "income" ? "income" : "expense")).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="field-row"><label className="field"><span>Dia do mês</span><input type="number" min="1" max="31" {...recurrenceForm.register("day")} /></label><label className="field"><span>Início</span><input type="month" {...recurrenceForm.register("startMonth")} /></label></div><label className="field"><span>Fim (opcional)</span><input type="month" {...recurrenceForm.register("endMonth")} /></label>{saveRecurrence.isError && <p className="field-error" role="alert">Não foi possível salvar o planejamento.</p>}{saveRecurrence.isSuccess && <p className="setup-saved" role="status">Recorrência adicionada. Você pode cadastrar outra.</p>}<button className="primary" disabled={saveRecurrence.isPending}>Adicionar recorrência</button></form><StepActions pending={persistStep.isPending} advance={advance} /></main>;

  const expenseCategories = categories.data?.items.filter((item) => item.kind === "expense") ?? [];
  if (step === 5) return <main className="setup narrow"><p className="eyebrow">Etapa opcional · 6 de 8</p><h1>Defina seus orçamentos</h1><p>Escolha uma categoria de despesa e informe o limite mensal. Você pode cadastrar vários limites antes de continuar.</p>{expenseCategories.length ? <form onSubmit={budgetForm.handleSubmit((v) => saveBudget.mutate(budgetSchema.parse(v)))}><label className="field"><span>Categoria</span><select {...budgetForm.register("categoryId")}><option value="">Selecione</option>{expenseCategories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><MoneyField label="Limite mensal" registration={budgetForm.register("amount")} error={budgetForm.formState.errors.amount} /><label className="field"><span>A partir do mês</span><input type="month" {...budgetForm.register("month")} /></label><label><input type="checkbox" {...budgetForm.register("asDefault")} /> Repetir este limite nos meses seguintes</label>{saveBudget.isError && <p className="field-error" role="alert">Não foi possível salvar o orçamento.</p>}{saveBudget.isSuccess && <p className="setup-saved" role="status">Orçamento salvo. Você pode cadastrar outro.</p>}<button className="primary" disabled={saveBudget.isPending}>Adicionar orçamento</button></form> : <div className="setup-facts"><div><strong>Sem categorias de despesa</strong><span>Crie uma categoria antes ou pule esta etapa.</span></div></div>}<StepActions pending={persistStep.isPending} advance={advance} /></main>;

  if (step === 6) return <main className="setup narrow"><p className="eyebrow">Etapa opcional · 7 de 8</p><h1>Recuperação dos dados</h1><p>Backups diários ficam no seu perfil e cópias manuais podem ser exportadas. A restauração sempre mostra uma prévia e exige confirmação.</p><div className="setup-facts"><div><strong>Automático</strong><span>Uma cópia diária é criada quando o aplicativo abre.</span></div><div><strong>Manual</strong><span>Exporte cópias pela tela Configurações e dados.</span></div></div><StepActions pending={persistStep.isPending} advance={advance} /></main>;

  return <main className="setup"><p className="eyebrow">Resumo · 8 de 8</p><h1>Configuração inicial concluída.</h1><p>Sua conta e as opções escolhidas estão salvas. Tudo pode ser ampliado ou alterado pelo menu do aplicativo.</p><div className="setup-facts"><div><strong>Saldo</strong><span>Parte da referência inicial e é atualizado por movimentos efetivados.</span></div><div><strong>Previsões</strong><span>Nunca são efetivadas automaticamente.</span></div><div><strong>Backup</strong><span>Uma cópia diária será mantida quando o app abrir.</span></div></div><button className="primary" disabled={persistStep.isPending} onClick={() => persistStep.mutate(8)}>Abrir visão geral</button></main>;
}
