"""domain schema

Revision ID: 0002_domain_schema
Revises: 0001_foundation
Create Date: 2026-09-09 15:44:44.494521
"""
from alembic import op
import sqlalchemy as sa


revision = '0002_domain_schema'
down_revision = '0001_foundation'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('institution', sa.String(length=120), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('reference_balance_minor', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("currency = 'BRL'", name='ck_accounts_currency_brl'),
    sa.CheckConstraint('reference_balance_minor BETWEEN -9007199254740991 AND 9007199254740991', name='ck_accounts_safe_balance'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index('ix_accounts_archived_at', ['archived_at'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('before_json', sa.Text(), nullable=True),
    sa.Column('after_json', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_events_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_audit_events_occurred_at', ['occurred_at'], unique=False)

    op.create_table('backup_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=False),
    sa.Column('alembic_revision', sa.String(length=64), nullable=False),
    sa.Column('backup_format_version', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('started','succeeded','failed')", name='ck_backup_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup_runs', schema=None) as batch_op:
        batch_op.create_index('ix_backup_runs_created_status', ['created_at', 'status'], unique=False)

    op.create_table('cash_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('signed_amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('transfer_id', sa.String(length=36), nullable=True),
    sa.Column('payment_id', sa.String(length=36), nullable=True),
    sa.Column('recurrence_occurrence_id', sa.String(length=36), nullable=True),
    sa.Column('refund_id', sa.String(length=36), nullable=True),
    sa.Column('reversal_of_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=True),
    sa.Column('source_connection_id', sa.String(length=160), nullable=True),
    sa.CheckConstraint("currency = 'BRL'", name='ck_cash_entries_currency_brl'),
    sa.CheckConstraint("kind IN ('income','expense','transfer_in','transfer_out','invoice_payment','refund','balance_adjustment')", name='ck_cash_entries_kind'),
    sa.CheckConstraint("source IN ('manual','opening','recurrence','file_import','bank_api')", name='ck_cash_entries_source'),
    sa.CheckConstraint("status IN ('planned','effective','cancelled','voided')", name='ck_cash_entries_status'),
    sa.CheckConstraint('signed_amount_minor BETWEEN -9007199254740991 AND 9007199254740991 AND signed_amount_minor <> 0', name='ck_cash_entries_safe_amount'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recurrence_occurrence_id'], ['recurrence_occurrences.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['refund_id'], ['refunds.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversal_of_id'], ['cash_entries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_entries', schema=None) as batch_op:
        batch_op.create_index('ix_cash_entries_account_date', ['account_id', 'effective_date'], unique=False)
        batch_op.create_index('ix_cash_entries_category', ['category_id'], unique=False)
        batch_op.create_index('ix_cash_entries_payment', ['payment_id'], unique=False)
        batch_op.create_index('ix_cash_entries_planned_date', ['planned_date'], unique=False)
        batch_op.create_index('ix_cash_entries_recurrence', ['recurrence_occurrence_id'], unique=False)
        batch_op.create_index('ix_cash_entries_status_source', ['status', 'source'], unique=False)
        batch_op.create_index('ix_cash_entries_transfer', ['transfer_id'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('income','expense')", name='ck_categories_kind'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index('ix_categories_kind_archived', ['kind', 'archived_at'], unique=False)

    op.create_table('idempotency_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('operation_scope', sa.String(length=160), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('result_status', sa.String(length=24), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('result_reference', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'operation_scope', name='uq_idempotency_key_scope')
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index('ix_idempotency_created_at', ['created_at'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reversal_of', sa.String(length=36), nullable=True),
    sa.Column('cash_entry_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint("currency = 'BRL'", name='ck_payments_currency_brl'),
    sa.CheckConstraint("status IN ('active','reversed')", name='ck_payments_status'),
    sa.CheckConstraint('amount_minor BETWEEN 0 AND 9007199254740991', name='ck_payments_safe_amount'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cash_entry_id'], ['cash_entries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversal_of'], ['payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cash_entry_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_account_date', ['account_id', 'paid_date'], unique=False)
        batch_op.create_index('uq_active_payment_invoice', ['invoice_id'], unique=True, sqlite_where=sa.text("status = 'active'"))

    op.create_table('planned_card_purchases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('expected_amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('estimated_invoice_month', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confirmed_purchase_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint("(status = 'confirmed' AND confirmed_purchase_id IS NOT NULL) OR (status <> 'confirmed' AND confirmed_purchase_id IS NULL)", name='ck_planned_purchases_confirmation_link'),
    sa.CheckConstraint("currency = 'BRL'", name='ck_planned_purchases_currency_brl'),
    sa.CheckConstraint("status IN ('planned','confirmed','cancelled')", name='ck_planned_purchases_status'),
    sa.CheckConstraint('expected_amount_minor BETWEEN 1 AND 9007199254740991', name='ck_planned_purchases_safe_amount'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['confirmed_purchase_id'], ['purchases.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirmed_purchase_id')
    )
    with op.batch_alter_table('planned_card_purchases', schema=None) as batch_op:
        batch_op.create_index('ix_planned_purchases_card_month', ['card_id', 'estimated_invoice_month'], unique=False)
        batch_op.create_index('ix_planned_purchases_category', ['category_id'], unique=False)
        batch_op.create_index('ix_planned_purchases_status_date', ['status', 'expected_date'], unique=False)

    op.create_table('purchases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('total_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('installment_count', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('recurrence_occurrence_id', sa.String(length=36), nullable=True),
    sa.Column('planned_card_purchase_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=True),
    sa.Column('source_connection_id', sa.String(length=160), nullable=True),
    sa.CheckConstraint("currency = 'BRL'", name='ck_purchases_currency_brl'),
    sa.CheckConstraint("source IN ('manual','opening','recurrence','file_import','bank_api')", name='ck_purchases_source'),
    sa.CheckConstraint("status IN ('confirmed','voided')", name='ck_purchases_status'),
    sa.CheckConstraint('installment_count >= 1 AND installment_count <= total_minor', name='ck_purchases_installments'),
    sa.CheckConstraint('total_minor BETWEEN 1 AND 9007199254740991', name='ck_purchases_safe_total'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['planned_card_purchase_id'], ['planned_card_purchases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recurrence_occurrence_id'], ['recurrence_occurrences.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planned_card_purchase_id')
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index('ix_purchases_card_date', ['card_id', 'purchase_date'], unique=False)
        batch_op.create_index('ix_purchases_category', ['category_id'], unique=False)
        batch_op.create_index('ix_purchases_recurrence', ['recurrence_occurrence_id'], unique=False)
        batch_op.create_index('ix_purchases_status_source', ['status', 'source'], unique=False)

    op.create_table('recurrence_occurrences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('occurrence_month', sa.String(length=7), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('expected_amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('exception', sa.Integer(), nullable=False),
    sa.Column('linked_cash_entry_id', sa.String(length=36), nullable=True),
    sa.Column('linked_purchase_id', sa.String(length=36), nullable=True),
    sa.Column('superseded_by_rule_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint("currency = 'BRL'", name='ck_recurrence_occurrences_currency_brl'),
    sa.CheckConstraint("status IN ('planned','confirmed','cancelled','superseded')", name='ck_recurrence_occurrences_status'),
    sa.CheckConstraint('expected_amount_minor BETWEEN 1 AND 9007199254740991', name='ck_recurrence_occurrences_safe_amount'),
    sa.ForeignKeyConstraint(['linked_cash_entry_id'], ['cash_entries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['linked_purchase_id'], ['purchases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_id'], ['recurrence_rules.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['superseded_by_rule_id'], ['recurrence_rules.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linked_cash_entry_id'),
    sa.UniqueConstraint('linked_purchase_id')
    )
    with op.batch_alter_table('recurrence_occurrences', schema=None) as batch_op:
        batch_op.create_index('ix_recurrence_occurrences_rule', ['rule_id'], unique=False)
        batch_op.create_index('ix_recurrence_occurrences_series_month', ['series_id', 'occurrence_month'], unique=False)
        batch_op.create_index('ix_recurrence_occurrences_status_date', ['status', 'expected_date'], unique=False)
        batch_op.create_index('uq_active_recurrence_series_month', ['series_id', 'occurrence_month'], unique=True, sqlite_where=sa.text("status <> 'superseded'"))

    op.create_table('refunds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.String(length=36), nullable=True),
    sa.Column('original_cash_entry_id', sa.String(length=36), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('recognition_date', sa.Date(), nullable=True),
    sa.Column('target_kind', sa.String(length=16), nullable=False),
    sa.Column('target_invoice_id', sa.String(length=36), nullable=True),
    sa.Column('target_account_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.CheckConstraint("(target_kind = 'invoice' AND target_invoice_id IS NOT NULL AND target_account_id IS NULL) OR (target_kind = 'account' AND target_account_id IS NOT NULL AND target_invoice_id IS NULL)", name='ck_refunds_single_target'),
    sa.CheckConstraint("currency = 'BRL'", name='ck_refunds_currency_brl'),
    sa.CheckConstraint("status IN ('planned','confirmed','cancelled')", name='ck_refunds_status'),
    sa.CheckConstraint("target_kind IN ('invoice','account')", name='ck_refunds_target_kind'),
    sa.CheckConstraint('(purchase_id IS NOT NULL AND original_cash_entry_id IS NULL) OR (purchase_id IS NULL AND original_cash_entry_id IS NOT NULL)', name='ck_refunds_single_origin'),
    sa.CheckConstraint('amount_minor BETWEEN 1 AND 9007199254740991', name='ck_refunds_safe_amount'),
    sa.ForeignKeyConstraint(['original_cash_entry_id'], ['cash_entries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_index('ix_refunds_cash_entry', ['original_cash_entry_id'], unique=False)
        batch_op.create_index('ix_refunds_purchase', ['purchase_id'], unique=False)
        batch_op.create_index('ix_refunds_status_date', ['status', 'recognition_date'], unique=False)

    op.create_table('budget_defaults',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('effective_from_month', sa.String(length=7), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.CheckConstraint("currency = 'BRL'", name='ck_budget_defaults_currency_brl'),
    sa.CheckConstraint('amount_minor BETWEEN 0 AND 9007199254740991', name='ck_budget_defaults_safe_amount'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'effective_from_month', name='uq_budget_defaults_category_month')
    )
    with op.batch_alter_table('budget_defaults', schema=None) as batch_op:
        batch_op.create_index('ix_budget_defaults_effective', ['effective_from_month'], unique=False)

    op.create_table('budgets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.CheckConstraint("currency = 'BRL'", name='ck_budgets_currency_brl'),
    sa.CheckConstraint('amount_minor BETWEEN 0 AND 9007199254740991', name='ck_budgets_safe_amount'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'month', name='uq_budgets_category_month')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index('ix_budgets_month', ['month'], unique=False)

    op.create_table('cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('limit_minor', sa.Integer(), nullable=False),
    sa.Column('closing_day', sa.Integer(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('default_account_id', sa.String(length=36), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("currency = 'BRL'", name='ck_cards_currency_brl'),
    sa.CheckConstraint('closing_day BETWEEN 1 AND 31', name='ck_cards_closing_day'),
    sa.CheckConstraint('due_day BETWEEN 1 AND 31', name='ck_cards_due_day'),
    sa.CheckConstraint('limit_minor BETWEEN 0 AND 9007199254740991', name='ck_cards_safe_limit'),
    sa.ForeignKeyConstraint(['default_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index('ix_cards_archived_at', ['archived_at'], unique=False)
        batch_op.create_index('ix_cards_default_account', ['default_account_id'], unique=False)

    op.create_table('transfers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('from_account_id', sa.String(length=36), nullable=False),
    sa.Column('to_account_id', sa.String(length=36), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reversal_of', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.CheckConstraint("currency = 'BRL'", name='ck_transfers_currency_brl'),
    sa.CheckConstraint("status IN ('planned','effective','cancelled','reversed')", name='ck_transfers_status'),
    sa.CheckConstraint('amount_minor BETWEEN 1 AND 9007199254740991', name='ck_transfers_safe_amount'),
    sa.CheckConstraint('from_account_id <> to_account_id', name='ck_transfers_distinct_accounts'),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversal_of'], ['transfers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.create_index('ix_transfers_from_date', ['from_account_id', 'effective_date'], unique=False)
        batch_op.create_index('ix_transfers_status', ['status'], unique=False)
        batch_op.create_index('ix_transfers_to_date', ['to_account_id', 'effective_date'], unique=False)

    op.create_table('coverage_intervals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('card_id', sa.String(length=36), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('complete','partial','unknown')", name='ck_coverage_intervals_status'),
    sa.CheckConstraint('(account_id IS NOT NULL AND card_id IS NULL) OR (account_id IS NULL AND card_id IS NOT NULL)', name='ck_coverage_intervals_owner'),
    sa.CheckConstraint('date_from <= date_to', name='ck_coverage_intervals_dates'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coverage_intervals', schema=None) as batch_op:
        batch_op.create_index('ix_coverage_intervals_account_dates', ['account_id', 'date_from', 'date_to'], unique=False)
        batch_op.create_index('ix_coverage_intervals_card_dates', ['card_id', 'date_from', 'date_to'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('reference_month', sa.String(length=7), nullable=False),
    sa.Column('closing_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.CheckConstraint("state IN ('open','closed','settled')", name='ck_invoices_state'),
    sa.CheckConstraint('closing_date < due_date', name='ck_invoices_dates'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'reference_month', name='uq_invoices_card_month')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('ix_invoices_card_due', ['card_id', 'due_date'], unique=False)
        batch_op.create_index('ix_invoices_state_due', ['state', 'due_date'], unique=False)

    op.create_table('recurrence_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('card_id', sa.String(length=36), nullable=True),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('start_month', sa.String(length=7), nullable=False),
    sa.Column('end_month', sa.String(length=7), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.CheckConstraint("(kind IN ('income','expense') AND account_id IS NOT NULL AND card_id IS NULL) OR (kind = 'card_purchase' AND card_id IS NOT NULL AND account_id IS NULL)", name='ck_recurrence_rules_target'),
    sa.CheckConstraint("currency = 'BRL'", name='ck_recurrence_rules_currency_brl'),
    sa.CheckConstraint("kind IN ('income','expense','card_purchase')", name='ck_recurrence_rules_kind'),
    sa.CheckConstraint('amount_minor BETWEEN 1 AND 9007199254740991', name='ck_recurrence_rules_safe_amount'),
    sa.CheckConstraint('day BETWEEN 1 AND 31', name='ck_recurrence_rules_day'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'version', name='uq_recurrence_rules_series_version')
    )
    with op.batch_alter_table('recurrence_rules', schema=None) as batch_op:
        batch_op.create_index('ix_recurrence_rules_account', ['account_id'], unique=False)
        batch_op.create_index('ix_recurrence_rules_card', ['card_id'], unique=False)
        batch_op.create_index('ix_recurrence_rules_series_active', ['series_id', 'active'], unique=False)

    op.create_table('installments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.String(length=36), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('category_id_snapshot', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('cancellation_date', sa.Date(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("currency = 'BRL'", name='ck_installments_currency_brl'),
    sa.CheckConstraint("status IN ('confirmed','cancelled','historical_settled')", name='ck_installments_status'),
    sa.CheckConstraint('amount_minor BETWEEN 1 AND 9007199254740991', name='ck_installments_safe_amount'),
    sa.ForeignKeyConstraint(['category_id_snapshot'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_id', 'installment_number', name='uq_installments_purchase_number')
    )
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.create_index('ix_installments_category', ['category_id_snapshot'], unique=False)
        batch_op.create_index('ix_installments_invoice_status', ['invoice_id', 'status'], unique=False)

    op.create_table('invoice_adjustments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('signed_amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('refund_id', sa.String(length=36), nullable=True),
    sa.Column('origin_invoice_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.CheckConstraint("currency = 'BRL'", name='ck_invoice_adjustments_currency_brl'),
    sa.CheckConstraint("kind IN ('opening','debit','refund','credit_carry')", name='ck_invoice_adjustments_kind'),
    sa.CheckConstraint("status IN ('active','cancelled','consumed')", name='ck_invoice_adjustments_status'),
    sa.CheckConstraint('signed_amount_minor BETWEEN -9007199254740991 AND 9007199254740991 AND signed_amount_minor <> 0', name='ck_invoice_adjustments_safe_amount'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['origin_invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['refund_id'], ['refunds.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_adjustments', schema=None) as batch_op:
        batch_op.create_index('ix_invoice_adjustments_category', ['category_id'], unique=False)
        batch_op.create_index('ix_invoice_adjustments_invoice_status', ['invoice_id', 'status'], unique=False)
        batch_op.create_index('uq_active_carry_origin', ['origin_invoice_id'], unique=True, sqlite_where=sa.text("kind = 'credit_carry' AND status = 'active'"))

    op.create_table('invoice_payment_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.CheckConstraint("status IN ('active','cancelled')", name='ck_invoice_payment_plans_status'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_payment_plans', schema=None) as batch_op:
        batch_op.create_index('ix_invoice_payment_plans_date', ['planned_date'], unique=False)
        batch_op.create_index('uq_active_invoice_payment_plan', ['invoice_id'], unique=True, sqlite_where=sa.text("status = 'active'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_payment_plans', schema=None) as batch_op:
        batch_op.drop_index('uq_active_invoice_payment_plan', sqlite_where=sa.text("status = 'active'"))
        batch_op.drop_index('ix_invoice_payment_plans_date')

    op.drop_table('invoice_payment_plans')
    with op.batch_alter_table('invoice_adjustments', schema=None) as batch_op:
        batch_op.drop_index('uq_active_carry_origin', sqlite_where=sa.text("kind = 'credit_carry' AND status = 'active'"))
        batch_op.drop_index('ix_invoice_adjustments_invoice_status')
        batch_op.drop_index('ix_invoice_adjustments_category')

    op.drop_table('invoice_adjustments')
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.drop_index('ix_installments_invoice_status')
        batch_op.drop_index('ix_installments_category')

    op.drop_table('installments')
    with op.batch_alter_table('recurrence_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_recurrence_rules_series_active')
        batch_op.drop_index('ix_recurrence_rules_card')
        batch_op.drop_index('ix_recurrence_rules_account')

    op.drop_table('recurrence_rules')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_invoices_state_due')
        batch_op.drop_index('ix_invoices_card_due')

    op.drop_table('invoices')
    with op.batch_alter_table('coverage_intervals', schema=None) as batch_op:
        batch_op.drop_index('ix_coverage_intervals_card_dates')
        batch_op.drop_index('ix_coverage_intervals_account_dates')

    op.drop_table('coverage_intervals')
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_index('ix_transfers_to_date')
        batch_op.drop_index('ix_transfers_status')
        batch_op.drop_index('ix_transfers_from_date')

    op.drop_table('transfers')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index('ix_cards_default_account')
        batch_op.drop_index('ix_cards_archived_at')

    op.drop_table('cards')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index('ix_budgets_month')

    op.drop_table('budgets')
    with op.batch_alter_table('budget_defaults', schema=None) as batch_op:
        batch_op.drop_index('ix_budget_defaults_effective')

    op.drop_table('budget_defaults')
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index('ix_refunds_status_date')
        batch_op.drop_index('ix_refunds_purchase')
        batch_op.drop_index('ix_refunds_cash_entry')

    op.drop_table('refunds')
    with op.batch_alter_table('recurrence_occurrences', schema=None) as batch_op:
        batch_op.drop_index('uq_active_recurrence_series_month', sqlite_where=sa.text("status <> 'superseded'"))
        batch_op.drop_index('ix_recurrence_occurrences_status_date')
        batch_op.drop_index('ix_recurrence_occurrences_series_month')
        batch_op.drop_index('ix_recurrence_occurrences_rule')

    op.drop_table('recurrence_occurrences')
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index('ix_purchases_status_source')
        batch_op.drop_index('ix_purchases_recurrence')
        batch_op.drop_index('ix_purchases_category')
        batch_op.drop_index('ix_purchases_card_date')

    op.drop_table('purchases')
    with op.batch_alter_table('planned_card_purchases', schema=None) as batch_op:
        batch_op.drop_index('ix_planned_purchases_status_date')
        batch_op.drop_index('ix_planned_purchases_category')
        batch_op.drop_index('ix_planned_purchases_card_month')

    op.drop_table('planned_card_purchases')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('uq_active_payment_invoice', sqlite_where=sa.text("status = 'active'"))
        batch_op.drop_index('ix_payments_account_date')

    op.drop_table('payments')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index('ix_idempotency_created_at')

    op.drop_table('idempotency_records')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('ix_categories_kind_archived')

    op.drop_table('categories')
    with op.batch_alter_table('cash_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_cash_entries_transfer')
        batch_op.drop_index('ix_cash_entries_status_source')
        batch_op.drop_index('ix_cash_entries_recurrence')
        batch_op.drop_index('ix_cash_entries_planned_date')
        batch_op.drop_index('ix_cash_entries_payment')
        batch_op.drop_index('ix_cash_entries_category')
        batch_op.drop_index('ix_cash_entries_account_date')

    op.drop_table('cash_entries')
    with op.batch_alter_table('backup_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_backup_runs_created_status')

    op.drop_table('backup_runs')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_events_occurred_at')
        batch_op.drop_index('ix_audit_events_entity')

    op.drop_table('audit_events')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_accounts_archived_at')

    op.drop_table('accounts')
    # ### end Alembic commands ###

